"""initial forward testing schema

Creates the 10 core tables of the forward testing simulator, plus their
indexes, foreign keys and CHECK constraints.

This revision is the Alembic equivalent of the hand-applied
``db/migrations/001_initial_schema.sql``. The two are verified to produce
identical PostgreSQL schemas. Use ONE of the two paths, not both:

* Manual SQL  -> tracked in the ``schema_migrations`` table
* Alembic     -> tracked in the ``alembic_version`` table

If you applied the SQL by hand and want to adopt Alembic afterwards, stamp the
database instead of running the upgrade, so nothing is created twice::

    alembic stamp 001

Revision ID: 001
Revises:
Create Date: 2026-08-19 16:57:49.993125
"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _is_postgres() -> bool:
    """True when running against PostgreSQL.

    Guards PL/pgSQL trigger DDL, which SQLite cannot parse.
    """
    return op.get_bind().dialect.name == "postgresql"



def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_data_cache',
    sa.Column('data_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=64), nullable=False),
    sa.Column('exchange', sa.String(length=16), server_default=sa.text("'NSE'"), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('high', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('low', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('close', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('volume', sa.Numeric(precision=20, scale=4), server_default=sa.text('0'), nullable=False),
    sa.Column('bid', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('ask', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('source', sa.String(length=32), server_default=sa.text("'mstock'"), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("timeframe IN ('1min','3min','5min','15min','30min','60min','1hour','day','week','month')", name='ck_mdc_timeframe'),
    sa.CheckConstraint('bid IS NULL OR ask IS NULL OR bid <= ask', name='ck_mdc_spread'),
    sa.CheckConstraint('high >= low AND high >= open AND high >= close AND low <= open AND low <= close', name='ck_mdc_ohlc'),
    sa.CheckConstraint('open > 0 AND high > 0 AND low > 0 AND close > 0', name='ck_mdc_prices_pos'),
    sa.CheckConstraint('volume >= 0', name='ck_mdc_volume'),
    sa.PrimaryKeyConstraint('data_id'),
    sa.UniqueConstraint('symbol', 'exchange', 'timeframe', 'ts', name='uq_mdc_bar')
    )
    op.create_index('ix_mdc_symbol_tf_ts', 'market_data_cache', ['symbol', 'timeframe', sa.literal_column('ts DESC')], unique=False)
    op.create_index('ix_mdc_ts', 'market_data_cache', [sa.literal_column('ts DESC')], unique=False)
    op.create_table('portfolios',
    sa.Column('portfolio_id', sa.String(length=36).with_variant(sa.UUID(as_uuid=False), 'postgresql'), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('initial_capital', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('current_cash', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('base_currency', sa.CHAR(length=3), server_default=sa.text("'INR'"), nullable=False),
    sa.Column('status', sa.String(length=16), server_default=sa.text("'active'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('active','paused','stopped')", name='ck_portfolios_status'),
    sa.CheckConstraint('initial_capital > 0', name='ck_portfolios_capital_pos'),
    sa.PrimaryKeyConstraint('portfolio_id'),
    sa.UniqueConstraint('name', name='uq_portfolios_name')
    )
    op.create_index('ix_portfolios_status', 'portfolios', ['status'], unique=False)
    op.create_table('equity_curve',
    sa.Column('equity_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('portfolio_id', sa.String(length=36).with_variant(sa.UUID(as_uuid=False), 'postgresql'), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_equity', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('cash', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('position_value', sa.Numeric(precision=20, scale=4), server_default=sa.text('0'), nullable=False),
    sa.Column('daily_pnl', sa.Numeric(precision=20, scale=4), server_default=sa.text('0'), nullable=False),
    sa.Column('cumulative_pnl', sa.Numeric(precision=20, scale=4), server_default=sa.text('0'), nullable=False),
    sa.Column('drawdown', sa.Numeric(precision=20, scale=4), server_default=sa.text('0'), nullable=False),
    sa.Column('drawdown_pct', sa.Numeric(precision=12, scale=6), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.portfolio_id'], name='fk_equity_portfolio', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('equity_id'),
    sa.UniqueConstraint('portfolio_id', 'ts', name='uq_equity_portfolio_ts')
    )
    op.create_index('ix_equity_portfolio_ts', 'equity_curve', ['portfolio_id', sa.literal_column('ts DESC')], unique=False)
    op.create_table('performance_metrics',
    sa.Column('metric_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('portfolio_id', sa.String(length=36).with_variant(sa.UUID(as_uuid=False), 'postgresql'), nullable=False),
    sa.Column('calculation_date', sa.Date(), nullable=False),
    sa.Column('total_trades', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('winning_trades', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('losing_trades', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('win_rate', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('avg_win', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('avg_loss', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('largest_win', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('largest_loss', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('profit_factor', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('expectancy', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('sharpe_ratio', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('sortino_ratio', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('max_drawdown', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('max_drawdown_percentage', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('total_return', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('total_return_percentage', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('total_commission', sa.Numeric(precision=20, scale=4), server_default=sa.text('0'), nullable=False),
    sa.Column('total_slippage', sa.Numeric(precision=20, scale=4), server_default=sa.text('0'), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('total_trades >= 0 AND winning_trades >= 0 AND losing_trades >= 0 AND winning_trades + losing_trades <= total_trades', name='ck_perf_counts'),
    sa.CheckConstraint('win_rate IS NULL OR (win_rate >= 0 AND win_rate <= 1)', name='ck_perf_win_rate'),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.portfolio_id'], name='fk_perf_portfolio', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('metric_id'),
    sa.UniqueConstraint('portfolio_id', 'calculation_date', name='uq_perf_portfolio_date')
    )
    op.create_index('ix_perf_portfolio_date', 'performance_metrics', ['portfolio_id', sa.literal_column('calculation_date DESC')], unique=False)
    op.create_table('positions',
    sa.Column('position_id', sa.String(length=36).with_variant(sa.UUID(as_uuid=False), 'postgresql'), nullable=False),
    sa.Column('portfolio_id', sa.String(length=36).with_variant(sa.UUID(as_uuid=False), 'postgresql'), nullable=False),
    sa.Column('symbol', sa.String(length=64), nullable=False),
    sa.Column('exchange', sa.String(length=16), server_default=sa.text("'NSE'"), nullable=False),
    sa.Column('position_type', sa.String(length=8), server_default=sa.text("'long'"), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=20, scale=8), server_default=sa.text('0'), nullable=False),
    sa.Column('average_entry_price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('current_price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('unrealized_pnl', sa.Numeric(precision=20, scale=4), server_default=sa.text('0'), nullable=False),
    sa.Column('realized_pnl', sa.Numeric(precision=20, scale=4), server_default=sa.text('0'), nullable=False),
    sa.Column('commission_total', sa.Numeric(precision=20, scale=4), server_default=sa.text('0'), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(length=8), server_default=sa.text("'open'"), nullable=False),
    sa.CheckConstraint("(status = 'closed' AND closed_at IS NOT NULL) OR (status = 'open' AND closed_at IS NULL)", name='ck_positions_closed_consistency'),
    sa.CheckConstraint("position_type IN ('long','short')", name='ck_positions_type'),
    sa.CheckConstraint("status = 'closed' OR (position_type = 'long' AND quantity >= 0) OR (position_type = 'short' AND quantity <= 0)", name='ck_positions_qty_sign'),
    sa.CheckConstraint("status IN ('open','closed')", name='ck_positions_status'),
    sa.CheckConstraint('average_entry_price >= 0', name='ck_positions_avgpx'),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.portfolio_id'], name='fk_positions_portfolio', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('position_id')
    )
    op.create_index('ix_positions_opened_at', 'positions', [sa.literal_column('opened_at DESC')], unique=False)
    op.create_index('ix_positions_portfolio_status', 'positions', ['portfolio_id', 'status'], unique=False)
    op.create_index('ix_positions_symbol', 'positions', ['symbol'], unique=False)
    op.create_index('uq_positions_one_open_per_symbol', 'positions', ['portfolio_id', 'symbol'], unique=True, postgresql_where=sa.text("status = 'open'"), sqlite_where=sa.text("status = 'open'"))
    op.create_table('system_logs',
    sa.Column('log_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('portfolio_id', sa.String(length=36).with_variant(sa.UUID(as_uuid=False), 'postgresql'), nullable=True),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('log_level', sa.String(length=16), nullable=False),
    sa.Column('component', sa.String(length=64), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('stack_trace', sa.Text(), nullable=True),
    sa.Column('context', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.CheckConstraint("log_level IN ('debug','info','warning','error','critical')", name='ck_logs_level'),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.portfolio_id'], name='fk_logs_portfolio', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index('ix_logs_component', 'system_logs', ['component', sa.literal_column('ts DESC')], unique=False)
    op.create_index('ix_logs_errors', 'system_logs', [sa.literal_column('ts DESC')], unique=False, postgresql_where=sa.text("log_level IN ('error','critical')"), sqlite_where=sa.text("log_level IN ('error','critical')"))
    op.create_index('ix_logs_level_ts', 'system_logs', ['log_level', sa.literal_column('ts DESC')], unique=False)
    op.create_index('ix_logs_portfolio_ts', 'system_logs', ['portfolio_id', sa.literal_column('ts DESC')], unique=False)
    op.create_index('ix_logs_ts', 'system_logs', [sa.literal_column('ts DESC')], unique=False)
    op.create_table('orders',
    sa.Column('order_id', sa.String(length=36).with_variant(sa.UUID(as_uuid=False), 'postgresql'), nullable=False),
    sa.Column('portfolio_id', sa.String(length=36).with_variant(sa.UUID(as_uuid=False), 'postgresql'), nullable=False),
    sa.Column('position_id', sa.String(length=36).with_variant(sa.UUID(as_uuid=False), 'postgresql'), nullable=True),
    sa.Column('symbol', sa.String(length=64), nullable=False),
    sa.Column('exchange', sa.String(length=16), server_default=sa.text("'NSE'"), nullable=False),
    sa.Column('side', sa.String(length=4), nullable=False),
    sa.Column('order_type', sa.String(length=16), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('filled_quantity', sa.Numeric(precision=20, scale=8), server_default=sa.text('0'), nullable=False),
    sa.Column('limit_price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('stop_price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('trailing_amount', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('average_fill_price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('time_in_force', sa.String(length=8), server_default=sa.text("'day'"), nullable=False),
    sa.Column('status', sa.String(length=16), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('client_order_id', sa.String(length=64), nullable=True),
    sa.Column('broker_order_id', sa.String(length=64), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('filled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("order_type <> 'trailing_stop' OR trailing_amount IS NOT NULL", name='ck_orders_trailing_required'),
    sa.CheckConstraint("order_type IN ('market','limit','stop','stop_limit','trailing_stop')", name='ck_orders_type'),
    sa.CheckConstraint("order_type NOT IN ('limit','stop_limit') OR limit_price IS NOT NULL", name='ck_orders_limit_price_required'),
    sa.CheckConstraint("order_type NOT IN ('stop','stop_limit') OR stop_price IS NOT NULL", name='ck_orders_stop_price_required'),
    sa.CheckConstraint("side IN ('buy','sell')", name='ck_orders_side'),
    sa.CheckConstraint("status <> 'filled' OR (filled_at IS NOT NULL AND filled_quantity = quantity)", name='ck_orders_filled_consistency'),
    sa.CheckConstraint("status <> 'rejected' OR rejection_reason IS NOT NULL", name='ck_orders_rejection_reason'),
    sa.CheckConstraint("status IN ('pending','partial','filled','cancelled','rejected')", name='ck_orders_status'),
    sa.CheckConstraint("time_in_force IN ('day','gtc','ioc','fok')", name='ck_orders_tif'),
    sa.CheckConstraint('filled_quantity >= 0 AND filled_quantity <= quantity', name='ck_orders_filled_qty'),
    sa.CheckConstraint('quantity > 0', name='ck_orders_qty_pos'),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.portfolio_id'], name='fk_orders_portfolio', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['position_id'], ['positions.position_id'], name='fk_orders_position', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_index('ix_orders_portfolio_status', 'orders', ['portfolio_id', 'status'], unique=False)
    op.create_index('ix_orders_position', 'orders', ['position_id'], unique=False)
    op.create_index('ix_orders_symbol_submitted', 'orders', ['symbol', sa.literal_column('submitted_at DESC')], unique=False)
    op.create_index('ix_orders_working', 'orders', ['portfolio_id', 'symbol'], unique=False, postgresql_where=sa.text("status IN ('pending','partial')"), sqlite_where=sa.text("status IN ('pending','partial')"))
    op.create_index('uq_orders_client_order_id', 'orders', ['portfolio_id', 'client_order_id'], unique=True, postgresql_where=sa.text('client_order_id IS NOT NULL'), sqlite_where=sa.text('client_order_id IS NOT NULL'))
    op.create_table('fills',
    sa.Column('fill_id', sa.String(length=36).with_variant(sa.UUID(as_uuid=False), 'postgresql'), nullable=False),
    sa.Column('order_id', sa.String(length=36).with_variant(sa.UUID(as_uuid=False), 'postgresql'), nullable=False),
    sa.Column('position_id', sa.String(length=36).with_variant(sa.UUID(as_uuid=False), 'postgresql'), nullable=True),
    sa.Column('symbol', sa.String(length=64), nullable=False),
    sa.Column('side', sa.String(length=4), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('fill_price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('commission', sa.Numeric(precision=20, scale=4), server_default=sa.text('0'), nullable=False),
    sa.Column('slippage_bps', sa.Numeric(precision=12, scale=6), server_default=sa.text('0'), nullable=False),
    sa.Column('slippage_amount', sa.Numeric(precision=20, scale=4), server_default=sa.text('0'), nullable=False),
    sa.Column('exchange_fees', sa.Numeric(precision=20, scale=4), server_default=sa.text('0'), nullable=False),
    sa.Column('regulatory_fees', sa.Numeric(precision=20, scale=4), server_default=sa.text('0'), nullable=False),
    sa.Column('liquidity_flag', sa.String(length=8), nullable=True),
    sa.Column('reference_price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('filled_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("liquidity_flag IS NULL OR liquidity_flag IN ('maker','taker')", name='ck_fills_liquidity'),
    sa.CheckConstraint("side IN ('buy','sell')", name='ck_fills_side'),
    sa.CheckConstraint('commission >= 0 AND exchange_fees >= 0 AND regulatory_fees >= 0', name='ck_fills_fees_nonneg'),
    sa.CheckConstraint('fill_price > 0', name='ck_fills_price_pos'),
    sa.CheckConstraint('quantity > 0', name='ck_fills_qty_pos'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], name='fk_fills_order', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['position_id'], ['positions.position_id'], name='fk_fills_position', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('fill_id')
    )
    op.create_index('ix_fills_filled_at', 'fills', [sa.literal_column('filled_at DESC')], unique=False)
    op.create_index('ix_fills_order', 'fills', ['order_id'], unique=False)
    op.create_index('ix_fills_position', 'fills', ['position_id'], unique=False)
    op.create_index('ix_fills_symbol', 'fills', ['symbol', sa.literal_column('filled_at DESC')], unique=False)
    op.create_table('strategy_signals',
    sa.Column('signal_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('portfolio_id', sa.String(length=36).with_variant(sa.UUID(as_uuid=False), 'postgresql'), nullable=False),
    sa.Column('symbol', sa.String(length=64), nullable=False),
    sa.Column('strategy_name', sa.String(length=64), nullable=True),
    sa.Column('signal_type', sa.String(length=8), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('strength', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('target_position', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('bar_ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('indicators_snapshot', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('executed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('order_id', sa.String(length=36).with_variant(sa.UUID(as_uuid=False), 'postgresql'), nullable=True),
    sa.Column('skip_reason', sa.Text(), nullable=True),
    sa.CheckConstraint("direction IN ('long','short','flat')", name='ck_signals_direction'),
    sa.CheckConstraint("signal_type IN ('entry','exit')", name='ck_signals_type'),
    sa.CheckConstraint('strength IS NULL OR (strength >= 0 AND strength <= 1)', name='ck_signals_strength'),
    sa.CheckConstraint('target_position IS NULL OR (target_position >= -1 AND target_position <= 1)', name='ck_signals_target'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], name='fk_signals_order', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.portfolio_id'], name='fk_signals_portfolio', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('signal_id')
    )
    op.create_index('ix_signals_indicators', 'strategy_signals', ['indicators_snapshot'], unique=False, postgresql_using='gin')
    op.create_index('ix_signals_portfolio_gen', 'strategy_signals', ['portfolio_id', sa.literal_column('generated_at DESC')], unique=False)
    op.create_index('ix_signals_symbol', 'strategy_signals', ['symbol', sa.literal_column('generated_at DESC')], unique=False)
    op.create_index('ix_signals_unexecuted', 'strategy_signals', ['portfolio_id'], unique=False, postgresql_where=sa.text('executed = false'), sqlite_where=sa.text('executed = 0'))
    op.create_table('trades',
    sa.Column('trade_id', sa.String(length=36).with_variant(sa.UUID(as_uuid=False), 'postgresql'), nullable=False),
    sa.Column('portfolio_id', sa.String(length=36).with_variant(sa.UUID(as_uuid=False), 'postgresql'), nullable=False),
    sa.Column('position_id', sa.String(length=36).with_variant(sa.UUID(as_uuid=False), 'postgresql'), nullable=True),
    sa.Column('symbol', sa.String(length=64), nullable=False),
    sa.Column('strategy_name', sa.String(length=64), nullable=True),
    sa.Column('direction', sa.String(length=8), server_default=sa.text("'long'"), nullable=False),
    sa.Column('entry_order_id', sa.String(length=36).with_variant(sa.UUID(as_uuid=False), 'postgresql'), nullable=True),
    sa.Column('exit_order_id', sa.String(length=36).with_variant(sa.UUID(as_uuid=False), 'postgresql'), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('exit_price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('entry_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('exit_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gross_pnl', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('net_pnl', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('commission_total', sa.Numeric(precision=20, scale=4), server_default=sa.text('0'), nullable=False),
    sa.Column('slippage_total', sa.Numeric(precision=20, scale=4), server_default=sa.text('0'), nullable=False),
    sa.Column('holding_period_minutes', sa.Integer(), nullable=True),
    sa.Column('return_percentage', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('exit_reason', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("direction IN ('long','short')", name='ck_trades_direction'),
    sa.CheckConstraint("exit_reason IS NULL OR exit_reason IN ('signal','stop_loss','take_profit','trailing_stop','time_stop','risk_limit','manual','eod_flat')", name='ck_trades_exit_reason'),
    sa.CheckConstraint('exit_time >= entry_time', name='ck_trades_time_order'),
    sa.CheckConstraint('quantity > 0', name='ck_trades_qty_pos'),
    sa.ForeignKeyConstraint(['entry_order_id'], ['orders.order_id'], name='fk_trades_entry_order', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['exit_order_id'], ['orders.order_id'], name='fk_trades_exit_order', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.portfolio_id'], name='fk_trades_portfolio', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['position_id'], ['positions.position_id'], name='fk_trades_position', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('trade_id')
    )
    op.create_index('ix_trades_net_pnl', 'trades', ['portfolio_id', 'net_pnl'], unique=False)
    op.create_index('ix_trades_portfolio_exit', 'trades', ['portfolio_id', sa.literal_column('exit_time DESC')], unique=False)
    op.create_index('ix_trades_strategy', 'trades', ['strategy_name'], unique=False)
    op.create_index('ix_trades_symbol', 'trades', ['symbol'], unique=False)
    # ### end Alembic commands ###

    # --- hand-written additions (autogenerate cannot see these) -------------
    # Triggers are invisible to Alembic's autogenerate, so the updated_at
    # maintenance below is maintained by hand and must stay in sync with
    # db/migrations/001_initial_schema.sql.
    if _is_postgres():
        op.execute(
            """
            CREATE OR REPLACE FUNCTION set_updated_at()
            RETURNS TRIGGER AS $$
            BEGIN
                NEW.updated_at = now();
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;
            """
        )
        for table in ("portfolios", "orders"):
            op.execute(f"DROP TRIGGER IF EXISTS trg_{table}_updated_at ON {table};")
            op.execute(
                f"""
                CREATE TRIGGER trg_{table}_updated_at
                    BEFORE UPDATE ON {table}
                    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
                """
            )


def downgrade() -> None:
    # --- hand-written teardown (mirrors the additions in upgrade) -----------
    if _is_postgres():
        for table in ("portfolios", "orders"):
            op.execute(f"DROP TRIGGER IF EXISTS trg_{table}_updated_at ON {table};")
        op.execute("DROP FUNCTION IF EXISTS set_updated_at();")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_trades_symbol', table_name='trades')
    op.drop_index('ix_trades_strategy', table_name='trades')
    op.drop_index('ix_trades_portfolio_exit', table_name='trades')
    op.drop_index('ix_trades_net_pnl', table_name='trades')
    op.drop_table('trades')
    op.drop_index('ix_signals_unexecuted', table_name='strategy_signals', postgresql_where=sa.text('executed = false'), sqlite_where=sa.text('executed = 0'))
    op.drop_index('ix_signals_symbol', table_name='strategy_signals')
    op.drop_index('ix_signals_portfolio_gen', table_name='strategy_signals')
    op.drop_index('ix_signals_indicators', table_name='strategy_signals', postgresql_using='gin')
    op.drop_table('strategy_signals')
    op.drop_index('ix_fills_symbol', table_name='fills')
    op.drop_index('ix_fills_position', table_name='fills')
    op.drop_index('ix_fills_order', table_name='fills')
    op.drop_index('ix_fills_filled_at', table_name='fills')
    op.drop_table('fills')
    op.drop_index('uq_orders_client_order_id', table_name='orders', postgresql_where=sa.text('client_order_id IS NOT NULL'), sqlite_where=sa.text('client_order_id IS NOT NULL'))
    op.drop_index('ix_orders_working', table_name='orders', postgresql_where=sa.text("status IN ('pending','partial')"), sqlite_where=sa.text("status IN ('pending','partial')"))
    op.drop_index('ix_orders_symbol_submitted', table_name='orders')
    op.drop_index('ix_orders_position', table_name='orders')
    op.drop_index('ix_orders_portfolio_status', table_name='orders')
    op.drop_table('orders')
    op.drop_index('ix_logs_ts', table_name='system_logs')
    op.drop_index('ix_logs_portfolio_ts', table_name='system_logs')
    op.drop_index('ix_logs_level_ts', table_name='system_logs')
    op.drop_index('ix_logs_errors', table_name='system_logs', postgresql_where=sa.text("log_level IN ('error','critical')"), sqlite_where=sa.text("log_level IN ('error','critical')"))
    op.drop_index('ix_logs_component', table_name='system_logs')
    op.drop_table('system_logs')
    op.drop_index('uq_positions_one_open_per_symbol', table_name='positions', postgresql_where=sa.text("status = 'open'"), sqlite_where=sa.text("status = 'open'"))
    op.drop_index('ix_positions_symbol', table_name='positions')
    op.drop_index('ix_positions_portfolio_status', table_name='positions')
    op.drop_index('ix_positions_opened_at', table_name='positions')
    op.drop_table('positions')
    op.drop_index('ix_perf_portfolio_date', table_name='performance_metrics')
    op.drop_table('performance_metrics')
    op.drop_index('ix_equity_portfolio_ts', table_name='equity_curve')
    op.drop_table('equity_curve')
    op.drop_index('ix_portfolios_status', table_name='portfolios')
    op.drop_table('portfolios')
    op.drop_index('ix_mdc_ts', table_name='market_data_cache')
    op.drop_index('ix_mdc_symbol_tf_ts', table_name='market_data_cache')
    op.drop_table('market_data_cache')
    # ### end Alembic commands ###